(lang dune 3.21)
(using rocq 0.11)

(generate_opam_files true)

(name impboot)

(homepage "https://github.com/myreen/imp_bootstrap")
(authors "Kacper Korban" "Magnus Myreen" "Clément Pit-Claudel")
(maintainers "Kacper Korban")
(bug_reports "https://github.com/myreen/imp_bootstrap/issues")
(license MIT)

(package
 (name impboot)
 (synopsis "Minimal verified bootstrapped compiler for an imperative language")
 (depends
  (rocq-prover (= 9.0.0))
  (coq-coqutil (= "dev"))
  (patat (= "dev"))
 ))
