(lang dune 3.21)
(using rocq 0.11)

(generate_opam_files true)

(name impboot)

(license MIT)

(pin
 (url "git+https://github.com/mit-plv/coqutil.git#2cf510214b6d56a3065b092789b0c8455ae2c263")
 (package
  (name coq-coqutil)
  (version dev)))

(package
 (name impboot)
 (synopsis "Minimal verified bootstrapped compiler for an imperative language")
 (depends
  (ocaml (= 4.14.2))
  (rocq-core (= 9.1.1))
  (rocq-stdlib (= 9.0.0))
  (coq-coqutil (= "dev"))
 ))
